# Generated by Django 5.1.2 on 2024-10-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(max_length=20),
        ),
    ]
